# name: Deploy Churn Endpoint

# on:
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     env:
#       MODEL_GROUP: nasir-churn-model-group
#       ENDPOINT_NAME: nasir-churn-endpoint

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.11"

#       - name: Install deps
#         run: |
#           python -m pip install --upgrade pip
#           pip install boto3

#       - name: Deploy latest model (Approved preferred, fallback allowed)
#         run: |
#           python pipelines/deploy.py \
#             --region "${{ secrets.AWS_REGION }}" \
#             --execution-role-arn "${{ secrets.SAGEMAKER_EXEC_ROLE_ARN }}" \
#             --model-package-group-name "${{ env.MODEL_GROUP }}" \
#             --endpoint-name "${{ env.ENDPOINT_NAME }}" \
#             --instance-type "ml.m5.large" \
#             --allow-unapproved
  













name: Deploy Aqeel Churn Endpoint

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      MODEL_GROUP: aqeel-churn-model-group
      ENDPOINT_NAME: aqeel-churn-endpoint

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
        
            # avoid SageMaker v3 modular packages confusion
          pip uninstall -y sagemaker sagemaker-core sagemaker-mlops sagemaker-serve sagemaker-train sagemaker-mlflow || true
        
            # install SageMaker v2 (has sagemaker.sklearn)
          pip install "sagemaker>=2.218.0,<3" "boto3>=1.28.0" "botocore>=1.31.0"
        
          python -c "import sagemaker, importlib.metadata as m; print('sagemaker:', m.version('sagemaker'))"
        

      - name: Deploy latest APPROVED model only
        run: |
          python pipelines/deploy.py \
            --region "${{ secrets.AWS_REGION }}" \
            --execution-role-arn "${{ secrets.SAGEMAKER_EXEC_ROLE_ARN }}" \
            --model-package-group-name "${{ env.MODEL_GROUP }}" \
            --endpoint-name "${{ env.ENDPOINT_NAME }}" \
            --instance-type "ml.m5.large"
